title: "Régis Bérenger Yao ABALOVI"
 <img src="ZZZ.jpg" width="280" alt="Régis partageant ses connaissances">
description: "Portfolio activist"
show_downloads: true
theme: jekyll-theme-cayman
lang: fr 
